# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UICalculator.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1175, 640)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setStyleSheet("background-color: white")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidgetCalculator = QtWidgets.QTabWidget(Form)
        self.tabWidgetCalculator.setObjectName("tabWidgetCalculator")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_calc_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calc_2.sizePolicy().hasHeightForWidth())
        self.widget_calc_2.setSizePolicy(sizePolicy)
        self.widget_calc_2.setMinimumSize(QtCore.QSize(300, 200))
        self.widget_calc_2.setObjectName("widget_calc_2")
        self.gridLayout_7.addWidget(self.widget_calc_2, 0, 3, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 3, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.groupBox_5)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_10.addWidget(self.browse_button, 0, 4, 1, 1)
        self.roll_angle = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.roll_angle.setObjectName("roll_angle")
        self.gridLayout_10.addWidget(self.roll_angle, 3, 1, 1, 1)
        self.pb_start_calc = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_start_calc.setMinimumSize(QtCore.QSize(200, 60))
        self.pb_start_calc.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_calc.setFont(font)
        self.pb_start_calc.setStyleSheet("color: rgb(85, 255, 127);")
        self.pb_start_calc.setObjectName("pb_start_calc")
        self.gridLayout_10.addWidget(self.pb_start_calc, 3, 4, 2, 1)
        self.file_name = QtWidgets.QLineEdit(self.groupBox_5)
        self.file_name.setObjectName("file_name")
        self.gridLayout_10.addWidget(self.file_name, 0, 1, 1, 3)
        self.mono_no = QtWidgets.QLabel(self.groupBox_5)
        self.mono_no.setText("")
        self.mono_no.setObjectName("mono_no")
        self.gridLayout_10.addWidget(self.mono_no, 4, 0, 1, 2)
        self.output = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setText("")
        self.output.setObjectName("output")
        self.gridLayout_10.addWidget(self.output, 3, 2, 2, 2)
        self.gridLayout_7.addWidget(self.groupBox_5, 2, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 4, 1, 2)
        self.widget_calc = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calc.sizePolicy().hasHeightForWidth())
        self.widget_calc.setSizePolicy(sizePolicy)
        self.widget_calc.setMinimumSize(QtCore.QSize(300, 200))
        self.widget_calc.setObjectName("widget_calc")
        self.gridLayout_7.addWidget(self.widget_calc, 0, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxCount(2147483647)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBox.setMaximum(10000000)
        self.spinBox.setSingleStep(1000)
        self.spinBox.setProperty("value", 100000)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.pb_scan = QtWidgets.QPushButton(self.groupBox)
        self.pb_scan.setMinimumSize(QtCore.QSize(200, 60))
        self.pb_scan.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_scan.setFont(font)
        self.pb_scan.setStyleSheet("color: rgb(85, 255, 127);")
        self.pb_scan.setObjectName("pb_scan")
        self.gridLayout.addWidget(self.pb_scan, 1, 3, 2, 1)
        self.gridLayout_7.addWidget(self.groupBox, 2, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_7.addWidget(self.widget, 0, 5, 1, 1)
        self.tabWidgetCalculator.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidgetCalculator, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidgetCalculator.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Self Seeding tools"))
        self.groupBox_5.setTitle(_translate("Form", "Calculate from file"))
        self.label.setText(_translate("Form", "File name:"))
        self.label_3.setText(_translate("Form", "Roll angle:"))
        self.browse_button.setText(_translate("Form", "Browse"))
        self.pb_start_calc.setText(_translate("Form", "Calculate from npz file"))
        self.groupBox_2.setTitle(_translate("Form", "Save"))
        self.pushButton_2.setText(_translate("Form", "Load state"))
        self.pushButton.setText(_translate("Form", "Save state"))
        self.groupBox.setTitle(_translate("Form", "Scan"))
        self.label_4.setText(_translate("Form", "N shots"))
        self.label_2.setText(_translate("Form", "Monochromator no:"))
        self.pb_scan.setText(_translate("Form", "Scan and calculate"))
        self.tabWidgetCalculator.setTabText(self.tabWidgetCalculator.indexOf(self.tab), _translate("Form", "Calculator"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
