# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\DESYcloud\_code\pyhirex\gui\UISettings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(847, 1002)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setStyleSheet("background-color: white")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_apply = QtWidgets.QPushButton(Form)
        self.pb_apply.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pb_apply.setFont(font)
        self.pb_apply.setObjectName("pb_apply")
        self.horizontalLayout.addWidget(self.pb_apply)
        self.pb_cancel = QtWidgets.QPushButton(Form)
        self.pb_cancel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.combo_server = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_server.setObjectName("combo_server")
        self.gridLayout_6.addWidget(self.combo_server, 1, 1, 1, 1)
        self.le_server = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_server.setObjectName("le_server")
        self.gridLayout_6.addWidget(self.le_server, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        self.le_logbook = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_logbook.setObjectName("le_logbook")
        self.gridLayout_6.addWidget(self.le_logbook, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        self.sb_nbunch_back = QtWidgets.QSpinBox(self.groupBox_3)
        self.sb_nbunch_back.setMinimum(1)
        self.sb_nbunch_back.setProperty("value", 20)
        self.sb_nbunch_back.setObjectName("sb_nbunch_back")
        self.gridLayout_6.addWidget(self.sb_nbunch_back, 2, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 2, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.sb_hrx_npx_sa1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_hrx_npx_sa1.setMinimum(10)
        self.sb_hrx_npx_sa1.setMaximum(5000)
        self.sb_hrx_npx_sa1.setProperty("value", 1280)
        self.sb_hrx_npx_sa1.setObjectName("sb_hrx_npx_sa1")
        self.gridLayout_3.addWidget(self.sb_hrx_npx_sa1, 4, 2, 1, 1)
        self.le_hirex_ch_sa1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_hirex_ch_sa1.setObjectName("le_hirex_ch_sa1")
        self.gridLayout_3.addWidget(self.le_hirex_ch_sa1, 0, 1, 1, 2)
        self.le_trans_ch_sa1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_trans_ch_sa1.setEnabled(True)
        self.le_trans_ch_sa1.setObjectName("le_trans_ch_sa1")
        self.gridLayout_3.addWidget(self.le_trans_ch_sa1, 1, 1, 1, 2)
        self.le_slow_xgm_sa1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_slow_xgm_sa1.setObjectName("le_slow_xgm_sa1")
        self.gridLayout_3.addWidget(self.le_slow_xgm_sa1, 3, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.le_fast_xgm_sa1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_fast_xgm_sa1.setObjectName("le_fast_xgm_sa1")
        self.gridLayout_3.addWidget(self.le_fast_xgm_sa1, 2, 1, 1, 2)
        self.le_ctrl_num_bunch_sa1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_ctrl_num_bunch_sa1.setObjectName("le_ctrl_num_bunch_sa1")
        self.gridLayout_3.addWidget(self.le_ctrl_num_bunch_sa1, 5, 1, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 7, 0, 1, 1)
        self.sb_hrx_npx_sa2 = QtWidgets.QSpinBox(self.groupBox)
        self.sb_hrx_npx_sa2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_hrx_npx_sa2.setMinimum(10)
        self.sb_hrx_npx_sa2.setMaximum(5000)
        self.sb_hrx_npx_sa2.setProperty("value", 1280)
        self.sb_hrx_npx_sa2.setObjectName("sb_hrx_npx_sa2")
        self.gridLayout_4.addWidget(self.sb_hrx_npx_sa2, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 8, 0, 1, 1)
        self.le_ctrl_num_bunch_sa2 = QtWidgets.QLineEdit(self.groupBox)
        self.le_ctrl_num_bunch_sa2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_sa2.setObjectName("le_ctrl_num_bunch_sa2")
        self.gridLayout_4.addWidget(self.le_ctrl_num_bunch_sa2, 8, 1, 1, 2)
        self.le_hirex_ch_sa2 = QtWidgets.QLineEdit(self.groupBox)
        self.le_hirex_ch_sa2.setObjectName("le_hirex_ch_sa2")
        self.gridLayout_4.addWidget(self.le_hirex_ch_sa2, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 4, 0, 1, 1)
        self.le_trans_ch_sa2 = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_trans_ch_sa2.setFont(font)
        self.le_trans_ch_sa2.setText("")
        self.le_trans_ch_sa2.setObjectName("le_trans_ch_sa2")
        self.gridLayout_4.addWidget(self.le_trans_ch_sa2, 4, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 1)
        self.le_fast_xgm_sa2 = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_fast_xgm_sa2.setFont(font)
        self.le_fast_xgm_sa2.setObjectName("le_fast_xgm_sa2")
        self.gridLayout_4.addWidget(self.le_fast_xgm_sa2, 5, 1, 1, 2)
        self.le_slow_xgm_sa2 = QtWidgets.QLineEdit(self.groupBox)
        self.le_slow_xgm_sa2.setObjectName("le_slow_xgm_sa2")
        self.gridLayout_4.addWidget(self.le_slow_xgm_sa2, 6, 1, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 4, 0, 1, 1)
        self.le_dynprop_max = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_dynprop_max.setObjectName("le_dynprop_max")
        self.gridLayout_11.addWidget(self.le_dynprop_max, 2, 1, 1, 2)
        self.sb_max_spec_min = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_max_spec_min.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sb_max_spec_min.setMaximum(1279)
        self.sb_max_spec_min.setObjectName("sb_max_spec_min")
        self.gridLayout_11.addWidget(self.sb_max_spec_min, 2, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 2, 0, 1, 1)
        self.sb_max_spec_max = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_max_spec_max.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sb_max_spec_max.setMinimum(1)
        self.sb_max_spec_max.setMaximum(1280)
        self.sb_max_spec_max.setProperty("value", 1280)
        self.sb_max_spec_max.setObjectName("sb_max_spec_max")
        self.gridLayout_11.addWidget(self.sb_max_spec_max, 2, 4, 1, 1)
        self.le_dynprop_integ = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_dynprop_integ.setObjectName("le_dynprop_integ")
        self.gridLayout_11.addWidget(self.le_dynprop_integ, 4, 1, 1, 4)
        self.sb_2d_hist_size = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_2d_hist_size.setMinimum(10)
        self.sb_2d_hist_size.setMaximum(100000)
        self.sb_2d_hist_size.setSingleStep(100)
        self.sb_2d_hist_size.setProperty("value", 1000)
        self.sb_2d_hist_size.setObjectName("sb_2d_hist_size")
        self.gridLayout_11.addWidget(self.sb_2d_hist_size, 0, 3, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 7, 0, 1, 1)
        self.sb_hrx_npx_sa3 = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_hrx_npx_sa3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_hrx_npx_sa3.setMinimum(10)
        self.sb_hrx_npx_sa3.setMaximum(5000)
        self.sb_hrx_npx_sa3.setProperty("value", 1280)
        self.sb_hrx_npx_sa3.setObjectName("sb_hrx_npx_sa3")
        self.gridLayout_9.addWidget(self.sb_hrx_npx_sa3, 7, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 8, 0, 1, 1)
        self.le_ctrl_num_bunch_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_ctrl_num_bunch_sa3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_sa3.setObjectName("le_ctrl_num_bunch_sa3")
        self.gridLayout_9.addWidget(self.le_ctrl_num_bunch_sa3, 8, 1, 1, 2)
        self.le_hirex_ch_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_hirex_ch_sa3.setObjectName("le_hirex_ch_sa3")
        self.gridLayout_9.addWidget(self.le_hirex_ch_sa3, 2, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 4, 0, 1, 1)
        self.le_trans_ch_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_trans_ch_sa3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_trans_ch_sa3.setFont(font)
        self.le_trans_ch_sa3.setText("")
        self.le_trans_ch_sa3.setObjectName("le_trans_ch_sa3")
        self.gridLayout_9.addWidget(self.le_trans_ch_sa3, 4, 1, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 6, 0, 1, 1)
        self.le_fast_xgm_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_fast_xgm_sa3.setFont(font)
        self.le_fast_xgm_sa3.setObjectName("le_fast_xgm_sa3")
        self.gridLayout_9.addWidget(self.le_fast_xgm_sa3, 5, 1, 1, 2)
        self.le_slow_xgm_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_slow_xgm_sa3.setObjectName("le_slow_xgm_sa3")
        self.gridLayout_9.addWidget(self.le_slow_xgm_sa3, 6, 1, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 3, 0, 1, 1)
        self.le_ph_energy_sa3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_ph_energy_sa3.setObjectName("le_ph_energy_sa3")
        self.gridLayout_9.addWidget(self.le_ph_energy_sa3, 3, 1, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 7, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 7, 0, 1, 1)
        self.sb_hrx_npx_sa3_scs = QtWidgets.QSpinBox(self.groupBox_6)
        self.sb_hrx_npx_sa3_scs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_hrx_npx_sa3_scs.setMinimum(10)
        self.sb_hrx_npx_sa3_scs.setMaximum(5000)
        self.sb_hrx_npx_sa3_scs.setProperty("value", 1280)
        self.sb_hrx_npx_sa3_scs.setObjectName("sb_hrx_npx_sa3_scs")
        self.gridLayout_12.addWidget(self.sb_hrx_npx_sa3_scs, 7, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 8, 0, 1, 1)
        self.le_ctrl_num_bunch_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_ctrl_num_bunch_sa3_scs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_sa3_scs.setObjectName("le_ctrl_num_bunch_sa3_scs")
        self.gridLayout_12.addWidget(self.le_ctrl_num_bunch_sa3_scs, 8, 1, 1, 2)
        self.le_hirex_ch_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_hirex_ch_sa3_scs.setObjectName("le_hirex_ch_sa3_scs")
        self.gridLayout_12.addWidget(self.le_hirex_ch_sa3_scs, 2, 1, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setEnabled(False)
        self.label_28.setObjectName("label_28")
        self.gridLayout_12.addWidget(self.label_28, 4, 0, 1, 1)
        self.le_trans_ch_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_trans_ch_sa3_scs.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_trans_ch_sa3_scs.setFont(font)
        self.le_trans_ch_sa3_scs.setText("")
        self.le_trans_ch_sa3_scs.setObjectName("le_trans_ch_sa3_scs")
        self.gridLayout_12.addWidget(self.le_trans_ch_sa3_scs, 4, 1, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.groupBox_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 6, 0, 1, 1)
        self.le_fast_xgm_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_fast_xgm_sa3_scs.setFont(font)
        self.le_fast_xgm_sa3_scs.setObjectName("le_fast_xgm_sa3_scs")
        self.gridLayout_12.addWidget(self.le_fast_xgm_sa3_scs, 5, 1, 1, 2)
        self.le_slow_xgm_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_slow_xgm_sa3_scs.setObjectName("le_slow_xgm_sa3_scs")
        self.gridLayout_12.addWidget(self.le_slow_xgm_sa3_scs, 6, 1, 1, 2)
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_12.addWidget(self.label_39, 3, 0, 1, 1)
        self.le_ph_energy_sa3_scs = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_ph_energy_sa3_scs.setObjectName("le_ph_energy_sa3_scs")
        self.gridLayout_12.addWidget(self.le_ph_energy_sa3_scs, 3, 1, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 5, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem6, 7, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_13.addWidget(self.label_31, 7, 0, 1, 1)
        self.sb_hrx_npx_sp2 = QtWidgets.QSpinBox(self.groupBox_7)
        self.sb_hrx_npx_sp2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_hrx_npx_sp2.setMinimum(10)
        self.sb_hrx_npx_sp2.setMaximum(5000)
        self.sb_hrx_npx_sp2.setProperty("value", 1280)
        self.sb_hrx_npx_sp2.setObjectName("sb_hrx_npx_sp2")
        self.gridLayout_13.addWidget(self.sb_hrx_npx_sp2, 7, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_13.addWidget(self.label_32, 8, 0, 1, 1)
        self.le_ctrl_num_bunch_sp2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_ctrl_num_bunch_sp2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_sp2.setObjectName("le_ctrl_num_bunch_sp2")
        self.gridLayout_13.addWidget(self.le_ctrl_num_bunch_sp2, 8, 1, 1, 2)
        self.le_hirex_ch_sp2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_hirex_ch_sp2.setObjectName("le_hirex_ch_sp2")
        self.gridLayout_13.addWidget(self.le_hirex_ch_sp2, 2, 1, 1, 2)
        self.label_33 = QtWidgets.QLabel(self.groupBox_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_13.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_7)
        self.label_34.setObjectName("label_34")
        self.gridLayout_13.addWidget(self.label_34, 4, 0, 1, 1)
        self.le_trans_ch_sp2 = QtWidgets.QLineEdit(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_trans_ch_sp2.setFont(font)
        self.le_trans_ch_sp2.setText("")
        self.le_trans_ch_sp2.setObjectName("le_trans_ch_sp2")
        self.gridLayout_13.addWidget(self.le_trans_ch_sp2, 4, 1, 1, 2)
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 6, 0, 1, 1)
        self.le_fast_xgm_sp2 = QtWidgets.QLineEdit(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_fast_xgm_sp2.setFont(font)
        self.le_fast_xgm_sp2.setObjectName("le_fast_xgm_sp2")
        self.gridLayout_13.addWidget(self.le_fast_xgm_sp2, 5, 1, 1, 2)
        self.le_slow_xgm_sp2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_slow_xgm_sp2.setObjectName("le_slow_xgm_sp2")
        self.gridLayout_13.addWidget(self.le_slow_xgm_sp2, 6, 1, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_50 = QtWidgets.QLabel(self.groupBox_9)
        self.label_50.setObjectName("label_50")
        self.gridLayout_16.addWidget(self.label_50, 2, 0, 1, 1)
        self.le_hirex_ch_test2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.le_hirex_ch_test2.setText("")
        self.le_hirex_ch_test2.setObjectName("le_hirex_ch_test2")
        self.gridLayout_16.addWidget(self.le_hirex_ch_test2, 2, 1, 1, 2)
        self.le_ctrl_num_bunch_test2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.le_ctrl_num_bunch_test2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_test2.setObjectName("le_ctrl_num_bunch_test2")
        self.gridLayout_16.addWidget(self.le_ctrl_num_bunch_test2, 4, 1, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.groupBox_9)
        self.label_49.setObjectName("label_49")
        self.gridLayout_16.addWidget(self.label_49, 4, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_9)
        self.label_53.setObjectName("label_53")
        self.gridLayout_16.addWidget(self.label_53, 3, 0, 1, 1)
        self.le_ph_energy_test2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.le_ph_energy_test2.setObjectName("le_ph_energy_test2")
        self.gridLayout_16.addWidget(self.le_ph_energy_test2, 3, 1, 1, 2)
        self.gridLayout_18.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 4, 0, 1, 1)
        self.le_ctrl_num_bunch_test1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.le_ctrl_num_bunch_test1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_test1.setObjectName("le_ctrl_num_bunch_test1")
        self.gridLayout_15.addWidget(self.le_ctrl_num_bunch_test1, 4, 1, 1, 2)
        self.le_hirex_ch_test1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.le_hirex_ch_test1.setText("")
        self.le_hirex_ch_test1.setObjectName("le_hirex_ch_test1")
        self.gridLayout_15.addWidget(self.le_hirex_ch_test1, 2, 1, 1, 2)
        self.label_43 = QtWidgets.QLabel(self.groupBox_8)
        self.label_43.setObjectName("label_43")
        self.gridLayout_15.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_8)
        self.label_46.setObjectName("label_46")
        self.gridLayout_15.addWidget(self.label_46, 3, 0, 1, 1)
        self.le_ph_energy_test1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.le_ph_energy_test1.setObjectName("le_ph_energy_test1")
        self.gridLayout_15.addWidget(self.le_ph_energy_test1, 3, 1, 1, 2)
        self.gridLayout_18.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.le_hirex_ch_test3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.le_hirex_ch_test3.setText("")
        self.le_hirex_ch_test3.setObjectName("le_hirex_ch_test3")
        self.gridLayout_17.addWidget(self.le_hirex_ch_test3, 2, 1, 1, 2)
        self.le_ctrl_num_bunch_test3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.le_ctrl_num_bunch_test3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_ctrl_num_bunch_test3.setObjectName("le_ctrl_num_bunch_test3")
        self.gridLayout_17.addWidget(self.le_ctrl_num_bunch_test3, 4, 1, 1, 2)
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setObjectName("label_56")
        self.gridLayout_17.addWidget(self.label_56, 4, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        self.label_57.setObjectName("label_57")
        self.gridLayout_17.addWidget(self.label_57, 2, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_10)
        self.label_60.setObjectName("label_60")
        self.gridLayout_17.addWidget(self.label_60, 3, 0, 1, 1)
        self.le_ph_energy_test3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.le_ph_energy_test3.setObjectName("le_ph_energy_test3")
        self.gridLayout_17.addWidget(self.le_ph_energy_test3, 3, 1, 1, 2)
        self.gridLayout_18.addWidget(self.groupBox_10, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem7, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem8, 2, 0, 1, 1)
        self.cb_style_def = QtWidgets.QComboBox(self.tab_5)
        self.cb_style_def.setObjectName("cb_style_def")
        self.gridLayout_10.addWidget(self.cb_style_def, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ocelot Interface"))
        self.pb_apply.setText(_translate("Form", "Apply"))
        self.pb_cancel.setText(_translate("Form", "Cancel"))
        self.groupBox_3.setTitle(_translate("Form", "Interface"))
        self.label_5.setText(_translate("Form", "LogBook"))
        self.le_server.setText(_translate("Form", "XFEL, XFEL_SIM"))
        self.le_logbook.setText(_translate("Form", "xfellog"))
        self.label_15.setText(_translate("Form", "Server"))
        self.label_40.setText(_translate("Form", "N bunches to capture background"))
        self.groupBox_2.setTitle(_translate("Form", "SASE1 HIREX"))
        self.label_9.setText(_translate("Form", "Fast XGM signal"))
        self.label_8.setText(_translate("Form", "Transmission DOOCS "))
        self.label_10.setText(_translate("Form", "Slow XGM signal"))
        self.label_11.setText(_translate("Form", "HIREX N pixels"))
        self.label_12.setText(_translate("Form", "CTRL NUM Bunches"))
        self.label_7.setText(_translate("Form", "HIREX sgnal"))
        self.groupBox.setTitle(_translate("Form", "SASE2 HIREX"))
        self.label_3.setText(_translate("Form", "Fast XGM signal"))
        self.label.setText(_translate("Form", "HIREX N pixels"))
        self.label_2.setText(_translate("Form", "CTRL NUM Bunches"))
        self.le_ctrl_num_bunch_sa2.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.le_hirex_ch_sa2.setText(_translate("Form", "XFEL.EXP/DAQ.GOTTHARD_MASTER/SA2_XTD6_HIREX/ADC"))
        self.label_4.setText(_translate("Form", "HIREX signal"))
        self.label_20.setText(_translate("Form", "Transmission DOOCS "))
        self.label_6.setText(_translate("Form", "Slow XGM signal"))
        self.label_14.setText(_translate("Form", "History size"))
        self.label_36.setText(_translate("Form", "DOOCS:  integral(aver_spectrum)"))
        self.label_37.setText(_translate("Form", "DOOCS: max(aver_spectrum)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "General"))
        self.groupBox_5.setTitle(_translate("Form", "SASE3 SQS Spectrometer | --SASE3"))
        self.label_16.setText(_translate("Form", "Fast XGM signal"))
        self.label_17.setText(_translate("Form", "HIREX N pixels"))
        self.label_19.setText(_translate("Form", "CTRL NUM Bunches"))
        self.le_ctrl_num_bunch_sa3.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.le_hirex_ch_sa3.setText(_translate("Form", "XFEL.EXP/DAQ.GOTTHARD_MASTER/SA2_XTD6_HIREX/ADC"))
        self.label_21.setText(_translate("Form", "Spectr. Intensity"))
        self.label_22.setText(_translate("Form", "Transmission DOOCS "))
        self.label_23.setText(_translate("Form", "Slow XGM signal"))
        self.label_38.setText(_translate("Form", "Spectr. PhotonEnergy"))
        self.groupBox_6.setTitle(_translate("Form", "SASE3 SCS Spertrometer | --SASE3_SCS"))
        self.label_24.setText(_translate("Form", "Fast XGM signal"))
        self.label_25.setText(_translate("Form", "HIREX N pixels"))
        self.label_26.setText(_translate("Form", "CTRL NUM Bunches"))
        self.le_ctrl_num_bunch_sa3_scs.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.le_hirex_ch_sa3_scs.setText(_translate("Form", "XFEL.EXP/DAQ.GOTTHARD_MASTER/SA2_XTD6_HIREX/ADC"))
        self.label_27.setText(_translate("Form", "Spectr. Intensity"))
        self.label_28.setText(_translate("Form", "Transmission DOOCS "))
        self.label_29.setText(_translate("Form", "Slow XGM signal"))
        self.label_39.setText(_translate("Form", "Spectr. PhotonEnergy"))
        self.groupBox_7.setTitle(_translate("Form", "Spertrometer 2"))
        self.label_30.setText(_translate("Form", "Fast XGM signal"))
        self.label_31.setText(_translate("Form", "HIREX N pixels"))
        self.label_32.setText(_translate("Form", "CTRL NUM Bunches"))
        self.le_ctrl_num_bunch_sp2.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.le_hirex_ch_sp2.setText(_translate("Form", "XFEL.EXP/DAQ.GOTTHARD_MASTER/SA2_XTD6_HIREX/ADC"))
        self.label_33.setText(_translate("Form", "Spectrometer signal"))
        self.label_34.setText(_translate("Form", "Transmission DOOCS "))
        self.label_35.setText(_translate("Form", "Slow XGM signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "More Instruments"))
        self.groupBox_9.setTitle(_translate("Form", "Test2 | --TEST2"))
        self.label_50.setText(_translate("Form", "Spectr. Intensity"))
        self.le_ctrl_num_bunch_test2.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.label_49.setText(_translate("Form", "CTRL NUM Bunches"))
        self.label_53.setText(_translate("Form", "Spectr. PhotonEnergy"))
        self.groupBox_8.setTitle(_translate("Form", "Test1 | --TEST1"))
        self.label_42.setText(_translate("Form", "CTRL NUM Bunches"))
        self.le_ctrl_num_bunch_test1.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.label_43.setText(_translate("Form", "Spectr. Intensity"))
        self.label_46.setText(_translate("Form", "Spectr. PhotonEnergy"))
        self.groupBox_10.setTitle(_translate("Form", "Test3 | --TEST3"))
        self.le_ctrl_num_bunch_test3.setText(_translate("Form", "XFEL.UTIL/BUNCH_PATTERN/CONTROL/NUM_BUNCHES_REQUESTED_2"))
        self.label_56.setText(_translate("Form", "CTRL NUM Bunches"))
        self.label_57.setText(_translate("Form", "Spectr. Intensity"))
        self.label_60.setText(_translate("Form", "Spectr. PhotonEnergy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Experimental Stuff"))
        self.label_18.setText(_translate("Form", "Chose style by default"))
        self.label_13.setText(_translate("Form", "* changes take effect after reboot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Appearance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

